import 'package:flutter/material.dart';

Map imageProductList = {
  "biryani": [
    {'image': const AssetImage('assets/image/biryani/bi(1).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(2).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/biryani/bi(19).jpg'), 'type': ''},
  ],
  "cake":[
    {'image': const AssetImage('assets/image/cake/ca(1).jpg'), 'type': 'chocolate cake'},
    {'image': const AssetImage('assets/image/cake/ca(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(5).jpg'), 'type': 'chocolate cake'},
    {'image': const AssetImage('assets/image/cake/ca(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(11).jpg'), 'type': 'chocolate cake'},
    {'image': const AssetImage('assets/image/cake/ca(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(31).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(34).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(35).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(36).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(37).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(38).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(39).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(40).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(41).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(42).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(43).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(44).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(45).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(46).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cake/ca(47).jpg'), 'type': ''},
  ],
  "custard":[
    {'image': const AssetImage('assets/image/custard/cd(1).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(2).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(3).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(4).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(5).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(6).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(7).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(8).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(9).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(10).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(11).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(12).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(13).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(14).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(15).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(16).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(17).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(18).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(19).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(20).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(21).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(22).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(23).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(24).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(25).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(26).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(27).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(28).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(29).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(30).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(31).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(32).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/custard/cd(33).jpeg'), 'type': ''},
  ],
  "fast food":[
    {'image': const AssetImage('assets/image/fast_food/ff(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(35).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(36).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(37).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(38).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(39).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(40).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(41).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(42).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(43).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(44).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(45).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(46).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(47).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(48).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(49).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(50).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(51).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(52).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(53).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(54).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(55).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(56).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(57).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/fast_food/ff(58).jpg'), 'type': ''},
  ],
  "jain_food":[
    {'image': const AssetImage('assets/image/jain_food/jf(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/jain_food/jf(24).jpg'), 'type': ''},

  ],
  "paratha":[
    {'image': const AssetImage('assets/image/paratha/p(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(31).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(34).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(35).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(36).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(37).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(38).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(39).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(40).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(41).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(42).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(43).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/paratha/p(44).jpg'), 'type': ''},
  ],
  "pasta":[
    {'image': const AssetImage('assets/image/pasta/pt(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pasta/pt(26).jpg'), 'type': ''},
  ],
  "pizza":[
    {'image': const AssetImage('assets/image/pizza/pz(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(31).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(34).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(35).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(36).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(37).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(38).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(39).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(40).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(41).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(42).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(43).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(44).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(45).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(46).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(47).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(48).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(49).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(50).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(51).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(52).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(53).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(54).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(55).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(56).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(58).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(59).jpeg'), 'type': ''},
    {'image': const AssetImage('assets/image/pizza/pz(60).jpeg'), 'type': ''},
  ],
  "sabji":[
    {'image': const AssetImage('assets/image/sabji/s(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(31).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(34).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sabji/s(35).jpg'), 'type': ''},

  ],
  "sweet":[
    {'image': const AssetImage('assets/image/sweet/st(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/sweet/st(29).jpg'), 'type': ''},
  ],
  "thali":[
    {'image': const AssetImage('assets/image/thali/t(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/thali/t(22).jpg'), 'type': ''},
  ],
  "cafe":[
    {'image': const AssetImage('assets/image/cafe/c(1).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(2).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(3).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(4).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(5).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(6).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(7).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(8).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(9).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(10).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(11).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(12).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(13).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(14).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(15).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(16).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(17).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(18).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(19).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(20).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(21).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(22).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(23).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(24).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(25).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(26).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(27).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(28).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(29).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(30).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(31).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(32).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(33).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(34).jpg'), 'type': ''},
    {'image': const AssetImage('assets/image/cafe/c(35).jpg'), 'type': ''},
  ],


};

// "":[
// {
// 'image':const AssetImage(''),
// 'type': ''
// },
// ],

// {
// 'image':const AssetImage(''),
// 'type': ''
// },

/*"":[
{
'image':const AssetImage(''),
'type': ''
},
],*/